### ISSUE TITLE
App showing another user's songs until you login

### ISSUE THREAD

**Issue by davoloid** [JamesTwisleton/MusicJournal#4]
If another user logs in to the app, when you reload the app from https://musicjournal-c3d3e.web.app/#_= or https://musicjournal-c3d3e.web.app/ you see those songs, until you go to https://musicjournal-c3d3e.web.app/login and relogin.

**Comment by JamesTwisleton** [comment]
I think this is because I've removed cookies from the auth flow so the login persists on the server without checking the clients session, will look into it

**Comment by JamesTwisleton** [comment]
After a lot of blood and toil I've managed to fix this (I hope!). Can you confirm?

**Comment by ChangoFoster** [comment]
Seems to all be working for me with the latest changes on main

**Comment by JamesTwisleton** [comment]
Ok I'm going to close this for now. Thanks all!
