### ISSUE TITLE
Login page behaviour

### ISSUE THREAD

**Issue by davoloid** [JamesTwisleton/MusicJournal#7]
If a user is logged in and authenticated by Spotify, the main page shows the song details, but no other features at present.

If they return to https://musicjournal-c3d3e.web.app/login there is no indicator that they are logged in.

If they click logout, there is no indicator that logout has been successful, and indeed returning to https://musicjournal-c3d3e.web.app/ shows the songs still, so appears that logout is not occurring.

**Comment by JamesTwisleton** [comment]
Important UX points! 

We could make it redirect to the recent tracks page (or wherever) if a user visits the login page and is already logged in :) 

logout needs rethinking

**Comment by ChangoFoster** [comment]
Put up a PR to make this a bit better. Might need another iteration once we've figured out how we want it to work.
